// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW-G2Dda1AiSj1QfuyDqQj9SpDCDodLZw',
    appId: '1:198128894396:web:fd57820ae6a7916c322bb9',
    messagingSenderId: '198128894396',
    projectId: 'fastcheck-adb4d',
    authDomain: 'fastcheck-adb4d.firebaseapp.com',
    storageBucket: 'fastcheck-adb4d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJqswzQ1Q2AUH8JDWW1oXbPO89Cyzv4vs',
    appId: '1:198128894396:android:8a0e627c06c445b4322bb9',
    messagingSenderId: '198128894396',
    projectId: 'fastcheck-adb4d',
    storageBucket: 'fastcheck-adb4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBddEjJekKIFivTLXMbAsv77iZvafbIf5I',
    appId: '1:198128894396:ios:9553b07705410fcb322bb9',
    messagingSenderId: '198128894396',
    projectId: 'fastcheck-adb4d',
    storageBucket: 'fastcheck-adb4d.firebasestorage.app',
    iosBundleId: 'com.example.fascheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBddEjJekKIFivTLXMbAsv77iZvafbIf5I',
    appId: '1:198128894396:ios:9553b07705410fcb322bb9',
    messagingSenderId: '198128894396',
    projectId: 'fastcheck-adb4d',
    storageBucket: 'fastcheck-adb4d.firebasestorage.app',
    iosBundleId: 'com.example.fascheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW-G2Dda1AiSj1QfuyDqQj9SpDCDodLZw',
    appId: '1:198128894396:web:3e0df7d9a2900e0a322bb9',
    messagingSenderId: '198128894396',
    projectId: 'fastcheck-adb4d',
    authDomain: 'fastcheck-adb4d.firebaseapp.com',
    storageBucket: 'fastcheck-adb4d.firebasestorage.app',
  );
}
