// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUQflnV2GaXGZVlO59LGy7zNH27AzdMtg',
    appId: '1:283147372379:web:c93cab5b81ded6e8e67c7e',
    messagingSenderId: '283147372379',
    projectId: 'visto-51cb7',
    authDomain: 'visto-51cb7.firebaseapp.com',
    storageBucket: 'visto-51cb7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR7MA7yYBIdlyxS_-lm9yTGjyd3tBY3VE',
    appId: '1:283147372379:android:b6485f91ea2163ade67c7e',
    messagingSenderId: '283147372379',
    projectId: 'visto-51cb7',
    storageBucket: 'visto-51cb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcp6tdHtDCNi6IUbJ4Unv1XMlr50bR9ic',
    appId: '1:283147372379:ios:3c8aa1809a604eace67c7e',
    messagingSenderId: '283147372379',
    projectId: 'visto-51cb7',
    storageBucket: 'visto-51cb7.firebasestorage.app',
    iosBundleId: 'com.example.fascheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcp6tdHtDCNi6IUbJ4Unv1XMlr50bR9ic',
    appId: '1:283147372379:ios:3c8aa1809a604eace67c7e',
    messagingSenderId: '283147372379',
    projectId: 'visto-51cb7',
    storageBucket: 'visto-51cb7.firebasestorage.app',
    iosBundleId: 'com.example.fascheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUQflnV2GaXGZVlO59LGy7zNH27AzdMtg',
    appId: '1:283147372379:web:4bed6764149d487be67c7e',
    messagingSenderId: '283147372379',
    projectId: 'visto-51cb7',
    authDomain: 'visto-51cb7.firebaseapp.com',
    storageBucket: 'visto-51cb7.firebasestorage.app',
  );

}